In [2]:
import pandas as pd  
import os

In [3]:
csv_path = os.path.join('..', 'Web Scrapping', 'WITS-Country-Timeseries.xlsx')

# Read the CSV file
df = pd.read_excel(csv_path, sheet_name="Country-Timeseries")  # Using pandas

In [4]:
df.head(50)

,Country Name,Indicator Name,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,GDP per capita (current US$),554.594735,621.912414,663.141053,651.987862,628.146804,592.476165,520.251955,530.149863,502.057099,500.522981,516.866797,363.674087,NaN
1,Albania,GDP per capita (current US$),4094.349699,4437.141146,4247.631356,4413.063397,4578.633208,3952.803584,4124.055390,4531.032207,5287.660817,5396.214227,5343.037704,6377.203096,6802.804519
2,Algeria,GDP per capita (current US$),4495.921455,5473.281801,5610.733306,5519.777576,5516.229463,4197.419971,3967.200660,4134.936099,4171.795309,4021.983608,3354.157303,3700.311195,4273.922183
3,Andorra,GDP per capita (current US$),48237.891173,51428.196955,44902.380765,44747.753864,45680.534990,38885.530324,39931.216982,40632.231554,42904.828456,41328.600499,37207.222000,42072.341103,41992.793358
4,Angola,GDP per capita (current US$),3496.784796,4511.153227,4962.552072,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158
5,Antigua and Barbuda,GDP per capita (current US$),13404.516016,13117.146941,13686.476585,13350.149137,14004.811212,14861.882707,15862.651663,16110.312400,17514.355864,18187.779712,15284.772384,16740.348196,18745.173509
6,Argentina,GDP per capita (current US$),10385.964432,12848.740476,13082.664326,13080.254732,12334.798245,13789.060425,12790.264064,14613.035715,11795.162885,9963.674231,8496.428157,10636.115530,13686.008674
7,Armenia,GDP per capita (current US$),3143.029482,3462.681774,3643.715404,3833.157071,4017.229913,3666.141825,3679.952349,4041.995072,4391.923274,4828.504889,4505.867746,4966.513471,7014.206592
8,Aruba,GDP per capita (current US$),24452.928363,26044.435933,25609.955724,26515.678080,26942.307976,28421.386493,28451.273745,29326.708058,30918.515218,31902.762582,24487.863569,29342.100730,NaN
9,Australia,GDP per capita (current US$),52132.469608,62598.686618,68047.378178,68156.386105,62515.314832,56708.961197,49876.712376,53934.154374,57206.990670,54941.065720,51722.069000,60444.502355,64491.429886
10,Austria,GDP per capita (current US$),46903.761585,51442.276246,48564.917335,50731.127254,51786.377175,44195.817595,45307.587862,47429.158456,51466.556563,50070.403348,48809.226876,53637.705711,52131.446659
11,Azerbaijan,GDP per capita (current US$),5843.533768,7189.815151,7495.861942,7875.344611,7890.835250,5500.504620,3880.686267,4147.198619,4739.795242,4805.753718,4229.910649,5408.045352,7736.701232
12,"Bahamas, The",GDP per capita (current US$),27046.657665,26644.926578,28059.655395,27389.601971,28720.662193,29724.953336,29675.535891,30708.987018,31483.978841,32279.011363,23998.268019,28260.432551,31458.300812
13,Bahrain,GDP per capita (current US$),21186.814329,23741.557463,25102.726349,25790.730312,25464.760098,22795.448858,22867.181120,24349.909870,25415.846625,25869.112913,23433.187236,26860.072502,30152.034684
14,Bangladesh,GDP per capita (current US$),776.859577,856.381887,876.818007,973.773900,1108.514957,1236.004398,1659.962489,1815.610191,1963.412707,2122.078386,2233.305893,2457.924049,2688.303950
15,Barbados,GDP per capita (current US$),16489.795822,16907.209259,16691.332636,16893.606270,16924.190340,16990.219467,17343.725440,17843.197928,18224.890592,19002.962381,16643.806579,17225.462304,20018.515151
16,Belarus,GDP per capita (current US$),6034.678852,6527.654969,6953.217307,7998.077953,8341.288104,5967.069185,5039.776032,5785.534975,6360.052060,6837.767232,6542.864540,7489.718947,7904.856243
17,Belgium,GDP per capita (current US$),44184.946354,47410.566928,44670.560685,46757.951856,47764.071512,41008.296719,42012.622719,44198.482391,47544.981147,46641.711658,45517.903818,51268.388037,49582.825365
18,Belize,GDP per capita (current US$),5397.291575,5521.366276,5645.895822,5887.933435,6068.088609,6142.478833,6148.706961,6100.994681,6059.162553,6210.565543,5266.876160,6228.267309,6968.361585
19,Benin,GDP per capita (current US$),1009.489494,1099.414311,1112.569535,1214.295566,1251.504765,1041.652523,1049.820303,1095.274459,1194.438214,1170.965533,1237.949295,1361.100749,1303.222014
20,Bermuda,GDP per capita (current US$),101875.284073,97774.162072,98431.865181,99471.638898,98467.683994,102005.625642,106885.878489,111820.581466,113050.736882,116153.166122,107791.886435,111774.669092,118845.621104
21,Bhutan,GDP per capita (current US$),2194.125870,2491.273456,2470.072136,2409.439989,2589.899141,2695.636904,2879.546572,3240.706326,3210.707814,3303.962309,3009.925516,3266.362774,NaN
22,Bolivia,GDP per capita (current US$),1922.058662,2304.982295,2562.466784,2853.797162,3022.462884,2975.648811,3013.502707,3280.008214,3471.006951,3472.380831,3068.812555,3345.196588,3523.273733
23,Bosnia and Herzegovina,GDP per capita (current US$),4506.933669,4980.906155,4688.345902,5025.240652,5196.969426,4654.609552,4917.263698,5327.393184,6024.491546,6094.723214,6095.102479,7230.198163,7585.375002
24,Botswana,GDP per capita (current US$),6041.732051,7080.778297,6392.987347,6436.603063,6844.032996,5869.737772,6411.551666,6705.341062,6947.817841,6691.161051,5875.070606,7238.796096,7737.654681
25,Brazil,GDP per capita (current US$),11249.293741,13200.558166,12327.515556,12258.564849,12071.404655,8783.214413,8680.735421,9896.717511,9121.020092,8845.323931,6923.700197,7696.785531,8917.673898
26,Brunei,GDP per capita (current US$),34609.699959,46139.106837,46844.196721,43950.057062,41035.773137,30681.437438,26762.037429,28186.983386,31241.023973,30748.320190,27179.344422,31448.913608,37152.466238
27,Bulgaria,GDP per capita (current US$),6862.757687,7856.985958,7431.014045,7686.629222,7912.520540,7081.102336,7574.191264,8386.589202,9451.850870,9878.768872,10153.476600,12222.235646,13772.476794
28,Burkina Faso,GDP per capita (current US$),627.270395,727.612475,733.972879,762.303780,767.371344,632.126686,665.786329,711.184544,779.202768,772.166878,833.244336,893.077196,832.884266
29,Burundi,GDP per capita (current US$),222.660583,236.451347,238.205945,241.547666,257.818557,289.359627,242.539527,244.145422,232.060617,216.972971,216.827417,221.157803,238.441876
30,Cambodia,GDP per capita (current US$),782.695739,880.310304,950.482545,1015.220881,1098.074538,1170.742816,1281.105971,1400.899265,1533.315985,1671.385400,1577.911740,1625.235022,1786.560819
31,Cameroon,GDP per capita (current US$),1383.813864,1497.926586,1433.723927,1559.139050,1631.713986,1399.675336,1426.065481,1479.862223,1594.060109,1538.687912,1539.130547,1666.932809,1588.478723
32,Canada,GDP per capita (current US$),47562.083425,52223.696112,52669.089963,52635.174958,50955.998323,43596.135537,42315.603706,45129.429298,46547.795182,46374.152752,43349.677856,52358.621641,54966.488836
33,Cape Verde,GDP per capita (current US$),3500.977452,3880.069182,3583.461717,3757.659953,3739.278279,3169.078915,3312.696757,3534.343583,3860.454811,3928.309096,3223.735602,3557.837775,3902.589049
34,Cayman Islands,GDP per capita (current US$),76873.195321,75435.615227,75466.135870,75685.358365,76610.647968,77295.845665,78858.279656,81255.112269,85231.775151,89846.321099,83897.505208,88475.600879,NaN
35,Central African Republic,GDP per capita (current US$),459.776982,515.209504,525.867504,352.226855,394.856933,351.879755,372.135456,414.740323,435.932296,426.408753,435.469248,461.137511,427.058096
36,Chad,GDP per capita (current US$),896.876704,988.194161,969.616142,980.083545,1017.787762,774.411603,691.980077,662.897473,720.265101,701.621201,643.772216,685.690315,716.804381
37,Chile,GDP per capita (current US$),12767.782041,14628.572457,15406.492836,15833.275919,14666.343117,13569.948127,13785.687598,15045.527851,15795.708141,14627.145016,13165.386343,16247.401015,15355.506497
38,China,GDP per capita (current US$),4550.473924,5614.385739,6300.582352,7020.385682,7636.074223,8016.446016,8094.390375,8817.045496,9905.406118,10143.860206,10408.719125,12617.504986,12720.215640
39,Colombia,GDP per capita (current US$),6392.758026,7392.943600,8096.801510,8263.641929,8167.472842,6228.651622,5936.261022,6449.970987,6782.037920,6436.509215,5304.289129,6182.707099,6630.282726
40,Comoros,GDP per capita (current US$),1384.063284,1526.832638,1483.951559,1595.989819,1608.687875,1322.936775,1357.266229,1414.586689,1531.337811,1510.797323,1519.586780,1577.470841,1484.892465
41,"Congo, Dem. Rep.",GDP per capita (current US$),324.827726,376.374981,412.776261,444.864357,472.266236,482.064568,456.027951,451.089089,546.212593,575.882781,524.666686,577.209215,586.464289
42,"Congo, Rep.",GDP per capita (current US$),2962.762480,3415.062376,3753.860925,3719.651037,3622.530074,2347.818507,1970.250199,2088.500299,2512.384167,2288.808086,1838.448124,2290.382994,2447.988989
43,Costa Rica,GDP per capita (current US$),8147.243985,9137.455102,9971.651656,10633.266560,10737.678875,11529.955174,11899.813978,12118.133618,12383.149947,12669.341162,12179.256674,12537.256746,13198.821717
44,Cote d'Ivoire,GDP per capita (current US$),1654.177959,1701.704641,1649.301615,1903.054229,2124.019430,1941.581898,1999.195372,2113.341525,2295.540335,2290.787379,2349.069882,2613.378893,2486.412194
45,Croatia,GDP per capita (current US$),13664.208839,14623.990531,13410.820810,13949.121768,13970.983227,12071.090955,12550.708860,13562.144049,15003.140681,15086.211740,14236.535245,17747.789286,18413.234682
46,Cuba,GDP per capita (current US$),5275.532601,6106.006792,6467.337914,6814.243844,7117.526910,7683.757891,8055.889907,8543.360968,8831.907222,9139.415856,9499.590202,NaN,NaN
47,Cyprus,GDP per capita (current US$),31105.027344,32485.802734,28991.929688,27797.453125,27244.343750,23487.218750,24715.142578,26697.005859,29419.886719,29417.921875,28035.984375,31552.035156,31283.505859
48,Czech Republic,GDP per capita (current US$),19960.068487,21871.266075,19870.801212,20133.169143,19890.919906,17829.698322,18575.232027,20636.199952,23424.480460,23664.847863,22992.879383,26822.514186,27638.373276
49,Denmark,GDP per capita (current US$),58041.398436,61753.647132,58507.508052,61191.193704,62548.984733,53254.856370,54663.998372,57610.098180,61591.928870,59592.980689,60915.424400,68007.756673,66983.132002

In [5]:
df.columns.tolist()

['Country Name',
 'Indicator Name',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022']

We need to filter out values from this dataset

In [6]:
df['Indicator Name'].unique()

array(['GDP per capita (current US$)'], dtype=object)

In [7]:
df.dtypes

Country Name       object
Indicator Name     object
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
2018              float64
2019              float64
2020              float64
2021              float64
2022              float64
dtype: object

In [8]:
df = df.set_index("Country Name")

# Select only numeric columns (excluding 'Indicator Name')
numeric_cols = df.select_dtypes(include=['number'])

# Fill NaN values with the respective country's mean
df[numeric_cols.columns] = numeric_cols.apply(lambda row: row.fillna(row.mean()), axis=1)

# Reset index to bring 'Country Name' back
df = df.reset_index()

In [9]:
df

,Country Name,Indicator Name,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,GDP per capita (current US$),554.594735,621.912414,663.141053,651.987862,628.146804,592.476165,520.251955,530.149863,502.057099,500.522981,516.866797,363.674087,553.815151
1,Albania,GDP per capita (current US$),4094.349699,4437.141146,4247.631356,4413.063397,4578.633208,3952.803584,4124.055390,4531.032207,5287.660817,5396.214227,5343.037704,6377.203096,6802.804519
2,Algeria,GDP per capita (current US$),4495.921455,5473.281801,5610.733306,5519.777576,5516.229463,4197.419971,3967.200660,4134.936099,4171.795309,4021.983608,3354.157303,3700.311195,4273.922183
3,Andorra,GDP per capita (current US$),48237.891173,51428.196955,44902.380765,44747.753864,45680.534990,38885.530324,39931.216982,40632.231554,42904.828456,41328.600499,37207.222000,42072.341103,41992.793358
4,Angola,GDP per capita (current US$),3496.784796,4511.153227,4962.552072,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,Venezuela,GDP per capita (current US$),13692.914967,10877.112364,12937.927597,12433.980785,15975.729375,13183.533018,13183.533018,13183.533018,13183.533018,13183.533018,13183.533018,13183.533018,13183.533018
189,Vietnam,GDP per capita (current US$),1684.011667,1953.556979,2190.232284,2367.499542,2558.778924,2595.234979,2760.717101,2992.071746,3267.225009,3491.091279,3586.347297,3756.489122,4163.514300
190,Yemen,GDP per capita (current US$),1249.063085,1284.617635,1349.990295,1497.747941,1557.601406,1488.416267,1069.816997,893.716573,701.714878,693.816484,583.875663,603.707959,676.928385
191,Zambia,GDP per capita (current US$),1469.361450,1644.456831,1729.647471,1840.320553,1724.576220,1307.909649,1249.923143,1495.752138,1475.199836,1268.120941,956.831747,1137.344395,1487.907764
192,Zimbabwe,GDP per capita (current US$),937.840340,1082.615773,1290.193957,1408.367810,1407.034291,1410.329173,1421.787791,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411,1266.996031

In [10]:
gdp_df=df.copy()

In [11]:
gdp_df.drop(['Indicator Name'], axis=1, inplace=True)

In [12]:
gdp_df.rename(columns={'Country Name': 'Country'},
          inplace=True, errors='raise')

In [14]:
pivoted_gdp_df = gdp_df.melt(id_vars=["Country"], var_name="Year", value_name="GDP per capita")

pivoted_gdp_df["Year"] = pd.to_numeric(pivoted_gdp_df["Year"])

In [15]:
pivoted_gdp_df=pivoted_gdp_df[(pivoted_gdp_df['Year']>=2013) & (pivoted_gdp_df['Year']<=2021)]

In [16]:
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Russian Federation', 'Russia')
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Egypt, Arab Rep.', 'Egypt')
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Ethiopia(excludes Eritrea)', 'Ethiopia')
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Gambia, The', 'Gambia')
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Hong Kong, China', 'Hong Kong')
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Iran, Islamic Rep.', 'Iran')
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Korea, Rep.', 'South Korea')
pivoted_gdp_df['Country'] = pivoted_gdp_df['Country'].replace('Serbia, FR(Serbia/Montenegro)', 'Serbia')

In [18]:
pivoted_gdp_df[pivoted_gdp_df['Country']=='South Korea']

          Country  Year  GDP per capita
675   South Korea  2013    27182.734310
868   South Korea  2014    29249.575221
1061  South Korea  2015    28732.231076
1254  South Korea  2016    29288.870439
1447  South Korea  2017    31616.843400
1640  South Korea  2018    33436.923065
1833  South Korea  2019    31902.416905
2026  South Korea  2020    31721.298018
2219  South Korea  2021    34997.781643

In [19]:
pivoted_gdp_df.to_csv('GDP_per_capita.csv',index=False)