In [66]:
import pandas as pd  
import os

In [67]:
csv_path = os.path.join('..', 'Web Scrapping', 'data_cts_intentional_homicide.xlsx')

# Read the CSV file
gihr_df = pd.read_excel(csv_path,header=2)  # Using pandas

In [68]:
gihr_df.head(50)

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
0,ARM,Armenia,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,35.0,CTS
1,CHE,Switzerland,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,28.0,CTS
2,COL,Colombia,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,15053.0,CTS
3,CZE,Czechia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,69.0,CTS
4,DEU,Germany,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,455.0,CTS
5,FIN,Finland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,70.0,CTS
6,GTM,Guatemala,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,2764.0,CTS
7,HND,Honduras,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,905.0,CTS
8,HUN,Hungary,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,229.0,CTS
9,ISL,Iceland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,1.0,CTS
10,ITA,Italy,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,864.0,CTS
11,JPN,Japan,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,259.0,CTS
12,LKA,Sri Lanka,Asia,Southern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,809.0,CTS
13,LTU,Lithuania,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,173.0,CTS
14,MNG,Mongolia,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,207.0,CTS
15,NOR,Norway,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,16.0,CTS
16,SRB,Serbia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,134.0,CTS
17,SVK,Slovakia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,53.0,CTS
18,SVN,Slovenia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,16.0,CTS
19,TUR,Türkiye,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,9891.0,CTS
20,ARM,Armenia,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,41.0,CTS
21,CHE,Switzerland,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,26.0,CTS
22,COL,Colombia,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,16476.0,CTS
23,CZE,Czechia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,55.0,CTS
24,DEU,Germany,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,489.0,CTS
25,FIN,Finland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,66.0,CTS
26,GTM,Guatemala,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,2649.0,CTS
27,HND,Honduras,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,1319.0,CTS
28,HUN,Hungary,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,204.0,CTS
29,ISL,Iceland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,1.0,CTS
30,ITA,Italy,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,806.0,CTS
31,JPN,Japan,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,243.0,CTS
32,LKA,Sri Lanka,Asia,Southern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,902.0,CTS
33,LTU,Lithuania,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,174.0,CTS
34,MNG,Mongolia,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,217.0,CTS
35,NOR,Norway,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,18.0,CTS
36,SRB,Serbia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,117.0,CTS
37,SVK,Slovakia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,47.0,CTS
38,SVN,Slovenia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,23.0,CTS
39,TUR,Türkiye,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,10389.0,CTS
40,ARM,Armenia,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,47.0,CTS
41,ATG,Antigua and Barbuda,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,3.0,CTS
42,AUT,Austria,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,29.0,CTS
43,BEL,Belgium,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,81.0,CTS
44,BLZ,Belize,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,55.0,CTS/MoI
45,BOL,Bolivia (Plurinational State of),Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,330.0,CTS
46,BTN,Bhutan,Asia,Southern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,21.0,CTS
47,CHE,Switzerland,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,28.0,CTS
48,COL,Colombia,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,15819.0,CTS
49,CZE,Czechia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,66.0,CTS

In [69]:
gihr_df.columns.tolist()

['Iso3_code',
 'Country',
 'Region',
 'Subregion',
 'Indicator',
 'Dimension',
 'Category',
 'Sex',
 'Age',
 'Year',
 'Unit of measurement',
 'VALUE',
 'Source']

In [70]:
gihr_df.drop(['Iso3_code','Region',
 'Subregion','Source'],axis=1,inplace=True)

We need to filter out values from this dataset

In [71]:
gihr_df['Dimension'].unique()

array(['by citizenship', 'Total', 'by relationship to perpetrator',
       'by situational context', 'by mechanisms', 'by location'],
      dtype=object)

In [72]:
gihr_df=gihr_df[gihr_df['Dimension']=='Total']

In [73]:
gihr_df

,Country,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE
1457,Aruba,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1458,Anguilla,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1459,Armenia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,178.000000
1460,Antigua and Barbuda,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1.000000
1461,Australia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,374.000000
...,...,...,...,...,...,...,...,...,...
118432,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2019,"Rate per 100,000 population",8.677549
118433,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2020,"Rate per 100,000 population",8.479234
118434,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2021,"Rate per 100,000 population",8.769468
118435,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2022,"Rate per 100,000 population",8.424728
118436,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2023,"Rate per 100,000 population",8.249462

In [74]:
gihr_df['Indicator'].unique()

array(['Victims of intentional homicide',
       'Persons arrested/suspected for intentional homicide',
       'Persons convicted for intentional homicide',
       'Death due to intentional homicide in prison',
       'Victims of Intentional Homicide - Regional Estimate'],
      dtype=object)

In [75]:
gihr_df=gihr_df[gihr_df['Indicator']=='Victims of intentional homicide']

In [76]:
gihr_df

,Country,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE
1457,Aruba,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1458,Anguilla,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1459,Armenia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,178.000000
1460,Antigua and Barbuda,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1.000000
1461,Australia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,374.000000
...,...,...,...,...,...,...,...,...,...
106341,Slovenia,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.000000
106342,Türkiye,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.874463
106343,Uruguay,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",1.919872
106344,Holy See,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.000000
106345,Saint Vincent and the Grenadines,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.000000

In [77]:
gihr_df['Sex'].unique()

array(['Total', 'Male', 'Female'], dtype=object)

In [78]:
gihr_df=gihr_df[gihr_df['Sex']=='Total']

In [79]:
gihr_df['Year'].unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023], dtype=int64)

In [80]:
gihr_df['Unit of measurement'].unique()

array(['Counts', 'Rate per 100,000 population'], dtype=object)

In [81]:
gihr_df=gihr_df[gihr_df['Unit of measurement']=='Counts']

In [82]:
gihr_df.head(50)

,Country,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE
1457,Aruba,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1458,Anguilla,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1459,Armenia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,178.000000
1460,Antigua and Barbuda,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1.000000
1461,Australia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,374.000000
1462,Austria,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,89.000000
1463,Azerbaijan,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,329.000000
1464,Belgium,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,103.672131
1465,Bulgaria,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,227.000000
1466,Bahamas,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,45.000000
1467,Bosnia and Herzegovina,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,73.000000
1468,Belarus,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,508.000000
1469,Bermuda,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1.000000
1470,Brazil,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,29301.189296
1471,Barbados,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,34.000000
1472,Bhutan,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,20.000000
1473,Canada,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,657.000000
1474,Switzerland,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,110.000000
1475,Colombia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,24330.000000
1476,Costa Rica,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,139.000000
1477,Cayman Islands,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,2.000000
1478,Cyprus,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,5.000000
1479,Germany,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,931.000000
1480,Denmark,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,41.000000
1481,Ecuador,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,892.000000
1482,Egypt,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,269.000000
1483,Spain,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,483.957992
1484,Estonia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,118.000000
1485,Finland,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,152.000000
1486,Fiji,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,32.000000
1487,France,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1355.000000
1488,United Kingdom (England and Wales),Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,554.000000
1489,United Kingdom (Northern Ireland),Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,99.728560
1490,United Kingdom (Scotland),Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,76.255516
1491,Georgia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,270.000000
1492,Greece,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,104.000000
1493,Guyana,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,90.000000
1494,"China, Hong Kong Special Administrative Region",Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,137.000000
1495,Honduras,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,495.532800
1496,Croatia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,137.000000
1497,Hungary,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,201.000000
1498,India,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,44162.000000
1499,Ireland,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,17.000000
1500,Iraq,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1168.000000
1501,Israel,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,147.000000
1502,Italy,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1794.000000
1503,Jamaica,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,544.000000
1504,Jordan,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,120.000000
1505,Japan,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,676.000000
1506,Kazakhstan,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1475.000000

In [83]:
gihr_df.columns.tolist()

['Country',
 'Indicator',
 'Dimension',
 'Category',
 'Sex',
 'Age',
 'Year',
 'Unit of measurement',
 'VALUE']

In [84]:
gihr_df.drop(['Indicator',
 'Dimension',
 'Category',
 'Sex',
 'Age', 'Unit of measurement'],axis=1,inplace=True)

In [85]:
gihr_df.head(50)

                                             Country  Year         VALUE
1457                                           Aruba  1990      0.000000
1458                                        Anguilla  1990      0.000000
1459                                         Armenia  1990    178.000000
1460                             Antigua and Barbuda  1990      1.000000
1461                                       Australia  1990    374.000000
1462                                         Austria  1990     89.000000
1463                                      Azerbaijan  1990    329.000000
1464                                         Belgium  1990    103.672131
1465                                        Bulgaria  1990    227.000000
1466                                         Bahamas  1990     45.000000
1467                          Bosnia and Herzegovina  1990     73.000000
1468                                         Belarus  1990    508.000000
1469                                         Bermuda  1990      1.000000
1470                                          Brazil  1990  29301.189296
1471                                        Barbados  1990     34.000000
1472                                          Bhutan  1990     20.000000
1473                                          Canada  1990    657.000000
1474                                     Switzerland  1990    110.000000
1475                                        Colombia  1990  24330.000000
1476                                      Costa Rica  1990    139.000000
1477                                  Cayman Islands  1990      2.000000
1478                                          Cyprus  1990      5.000000
1479                                         Germany  1990    931.000000
1480                                         Denmark  1990     41.000000
1481                                         Ecuador  1990    892.000000
1482                                           Egypt  1990    269.000000
1483                                           Spain  1990    483.957992
1484                                         Estonia  1990    118.000000
1485                                         Finland  1990    152.000000
1486                                            Fiji  1990     32.000000
1487                                          France  1990   1355.000000
1488              United Kingdom (England and Wales)  1990    554.000000
1489               United Kingdom (Northern Ireland)  1990     99.728560
1490                       United Kingdom (Scotland)  1990     76.255516
1491                                         Georgia  1990    270.000000
1492                                          Greece  1990    104.000000
1493                                          Guyana  1990     90.000000
1494  China, Hong Kong Special Administrative Region  1990    137.000000
1495                                        Honduras  1990    495.532800
1496                                         Croatia  1990    137.000000
1497                                         Hungary  1990    201.000000
1498                                           India  1990  44162.000000
1499                                         Ireland  1990     17.000000
1500                                            Iraq  1990   1168.000000
1501                                          Israel  1990    147.000000
1502                                           Italy  1990   1794.000000
1503                                         Jamaica  1990    544.000000
1504                                          Jordan  1990    120.000000
1505                                           Japan  1990    676.000000
1506                                      Kazakhstan  1990   1475.000000

In [86]:
all_years = range(2003, 2024)  # 2021 inclusive

# Create a pivot table with countries as rows and years as columns
pivot_df = (
    gihr_df.pivot_table(
        index='Country',
        columns='Year',
        values='VALUE',
        aggfunc='first'  # Takes the first occurrence if duplicates exist
    )
    .reindex(columns=all_years)  # Ensure all years are present as columns
    .sort_index(axis=0)  # Sort countries alphabetically
    .reset_index()       # Move Country from index to column
)

# Rename the columns to match your requirements
pivot_df.columns.name = None  # Remove the 'Year' label from columns
pivot_df = pivot_df.rename(columns={'Country': 'Country'})

In [87]:
pivot_df.head(50)

,Country,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,1115.0,983.0,1231.0,...,NaN,3367.0,2318.0,2424.0,2474.0,2712.0,2570.0,1613.0,NaN,NaN
1,Albania,166.0,131.0,154.0,95.0,105.0,93.0,85.0,119.0,142.0,...,134.0,64.0,79.0,58.0,66.0,65.0,61.0,66.0,48.0,39.0
2,Algeria,NaN,NaN,NaN,312.0,271.0,328.0,277.0,254.0,280.0,...,577.0,546.0,542.0,524.0,568.0,519.0,654.0,695.0,795.0,536.0
3,American Samoa,3.0,4.0,6.0,4.0,1.0,3.0,2.0,5.0,5.0,...,3.0,4.0,0.0,7.0,13.0,0.0,NaN,NaN,NaN,NaN
4,Andorra,NaN,1.0,NaN,NaN,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
5,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.0,...,NaN,1254.0,1196.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Anguilla,2.0,1.0,0.0,5.0,4.0,1.0,1.0,0.0,0.0,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Antigua and Barbuda,5.0,4.0,3.0,11.0,17.0,16.0,16.0,6.0,NaN,...,NaN,NaN,NaN,20.0,12.0,3.0,9.0,16.0,10.0,NaN
8,Argentina,2967.0,2338.0,2198.0,2111.0,2139.0,2371.0,2642.0,2384.0,2511.0,...,3228.0,2837.0,2625.0,2317.0,2384.0,2308.0,2418.0,2094.0,1961.0,NaN
9,Armenia,NaN,83.0,58.0,79.0,77.0,97.0,97.0,56.0,71.0,...,72.0,75.0,87.0,70.0,50.0,73.0,52.0,61.0,NaN,NaN
10,Aruba,4.0,2.0,6.0,5.0,3.0,5.0,4.0,4.0,2.0,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Australia,302.0,263.0,259.0,281.0,255.0,261.0,263.0,231.0,248.0,...,243.0,236.0,227.0,208.0,221.0,225.0,221.0,193.0,220.0,226.0
12,Austria,50.0,59.0,54.0,61.0,45.0,58.0,51.0,61.0,77.0,...,42.0,44.0,54.0,70.0,86.0,77.0,65.0,65.0,79.0,80.0
13,Azerbaijan,NaN,NaN,NaN,NaN,189.0,192.0,NaN,206.0,211.0,...,236.0,211.0,169.0,182.0,197.0,168.0,230.0,197.0,245.0,NaN
14,Bahamas,50.0,44.0,52.0,61.0,78.0,73.0,87.0,94.0,127.0,...,122.0,146.0,111.0,122.0,91.0,95.0,73.0,119.0,128.0,NaN
15,Bahrain,NaN,NaN,NaN,NaN,4.0,6.0,13.0,2.0,12.0,...,9.0,3.0,4.0,6.0,5.0,4.0,0.0,1.0,3.0,NaN
16,Bangladesh,3471.0,3902.0,3592.0,4166.0,3863.0,4099.0,4219.0,3988.0,3966.0,...,4514.0,4035.0,3591.0,3549.0,3830.0,NaN,NaN,NaN,NaN,NaN
17,Barbados,33.0,22.0,29.0,35.0,25.0,23.0,19.0,31.0,27.0,...,25.0,31.0,22.0,30.0,28.0,48.0,41.0,32.0,43.0,NaN
18,Belarus,NaN,NaN,NaN,NaN,649.0,552.0,487.0,401.0,373.0,...,340.0,326.0,307.0,240.0,226.0,225.0,NaN,NaN,NaN,NaN
19,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.0,NaN,NaN
20,Belize,67.0,79.0,81.0,92.0,97.0,103.0,97.0,129.0,124.0,...,123.0,119.0,138.0,142.0,143.0,134.0,102.0,125.0,113.0,NaN
21,Bermuda,2.0,1.0,2.0,3.0,3.0,5.0,6.0,7.0,8.0,...,4.0,4.0,8.0,5.0,5.0,0.0,7.0,7.0,9.0,4.0
22,Bhutan,5.0,15.0,11.0,9.0,14.0,18.0,16.0,16.0,32.0,...,NaN,12.0,9.0,13.0,9.0,8.0,19.0,NaN,NaN,NaN
23,Bolivia (Plurinational State of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,543.0,642.0,747.0,574.0,497.0,428.0,418.0,485.0,535.0
24,Bosnia and Herzegovina,NaN,68.0,NaN,NaN,66.0,66.0,71.0,56.0,51.0,...,50.0,57.0,45.0,42.0,39.0,42.0,43.0,32.0,35.0,39.0
25,Botswana,312.0,259.0,291.0,261.0,280.0,281.0,289.0,303.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,221.0,273.0,NaN,NaN
26,Brazil,51064.0,48394.0,47593.0,49165.0,47731.0,50135.0,51461.0,52289.0,52233.0,...,59733.0,58184.0,61208.0,63788.0,55980.0,44073.0,47722.0,45562.0,44367.0,NaN
27,British Virgin Islands,2.0,4.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Brunei Darussalam,3.0,2.0,2.0,3.0,3.0,1.0,3.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Bulgaria,247.0,244.0,199.0,186.0,177.0,172.0,150.0,148.0,128.0,...,112.0,126.0,79.0,103.0,92.0,83.0,69.0,89.0,76.0,74.0
30,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,564.0,461.0,635.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Cabo Verde,15.0,21.0,44.0,35.0,NaN,NaN,NaN,NaN,NaN,...,65.0,46.0,62.0,38.0,31.0,33.0,36.0,NaN,NaN,NaN
32,Cambodia,509.0,511.0,448.0,400.0,393.0,333.0,331.0,331.0,268.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Cameroon,1002.0,NaN,NaN,NaN,NaN,776.0,1277.0,999.0,835.0,...,NaN,861.0,787.0,1004.0,NaN,NaN,1202.0,NaN,NaN,NaN
34,Canada,549.0,625.0,664.0,608.0,597.0,614.0,610.0,557.0,609.0,...,525.0,611.0,616.0,665.0,662.0,689.0,764.0,796.0,874.0,NaN
35,Cayman Islands,3.0,5.0,3.0,1.0,2.0,4.0,8.0,9.0,NaN,...,5.0,NaN,NaN,3.0,7.0,2.0,3.0,NaN,NaN,NaN
36,Chile,513.0,NaN,576.0,590.0,616.0,588.0,630.0,541.0,636.0,...,438.0,419.0,620.0,779.0,825.0,924.0,1115.0,906.0,1322.0,NaN
37,China,24393.0,24711.0,20770.0,17973.0,16119.0,14811.0,14667.0,13410.0,12015.0,...,10083.0,9200.0,8634.0,7990.0,7525.0,7379.0,7157.0,NaN,NaN,NaN
38,"China, Hong Kong Special Administrative Region",52.0,45.0,34.0,35.0,18.0,36.0,47.0,35.0,17.0,...,27.0,22.0,28.0,24.0,48.0,24.0,22.0,23.0,30.0,NaN
39,"China, Macao Special Administrative Region",8.0,4.0,4.0,10.0,6.0,4.0,5.0,2.0,4.0,...,1.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,4.0
40,Colombia,23523.0,20210.0,18111.0,17479.0,17198.0,16140.0,15817.0,15459.0,16127.0,...,13343.0,12783.0,12402.0,12298.0,11678.0,11678.0,11508.0,13144.0,13097.0,NaN
41,Cook Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Costa Rica,300.0,280.0,335.0,351.0,369.0,512.0,525.0,527.0,474.0,...,477.0,557.0,578.0,603.0,585.0,563.0,570.0,588.0,656.0,906.0
43,Croatia,69.0,83.0,68.0,74.0,62.0,71.0,49.0,62.0,49.0,...,36.0,37.0,44.0,46.0,24.0,33.0,40.0,33.0,31.0,NaN
44,Cuba,642.0,660.0,684.0,576.0,568.0,515.0,565.0,505.0,534.0,...,600.0,619.0,572.0,516.0,491.0,500.0,NaN,NaN,NaN,NaN
45,Curaçao,43.0,41.0,26.0,18.0,26.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Cyprus,NaN,16.0,20.0,15.0,13.0,9.0,19.0,8.0,9.0,...,11.0,15.0,13.0,7.0,15.0,15.0,15.0,16.0,8.0,11.0
47,Czechia,163.0,134.0,108.0,130.0,126.0,114.0,94.0,103.0,86.0,...,81.0,88.0,65.0,66.0,NaN,91.0,64.0,46.0,88.0,83.0
48,Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,46.0,...,74.0,62.0,56.0,71.0,58.0,50.0,48.0,37.0,58.0,NaN
49,Dominica,8.0,8.0,8.0,5.0,7.0,7.0,13.0,15.0,6.0,...,9.0,9.0,16.0,19.0,13.0,13.0,15.0,10.0,19.0,NaN

In [88]:
# Fill NaN values with the respective country's mean
pivot_df = pivot_df.set_index("Country").apply(lambda row: row.fillna(row.mean()), axis=1).reset_index()

In [93]:
pivot_df.head(50)

,Country,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,2068.636364,2068.636364,2068.636364,2068.636364,2068.636364,2068.636364,1115.000000,983.000000,1231.000000,...,2068.636364,3367.000000,2318.000000,2424.000000,2474.000000,2712.000000,2570.000000,1613.000000,2068.636364,2068.636364
1,Albania,166.000000,131.000000,154.000000,95.000000,105.000000,93.000000,85.000000,119.000000,142.000000,...,134.000000,64.000000,79.000000,58.000000,66.000000,65.000000,61.000000,66.000000,48.000000,39.000000
2,Algeria,482.277778,482.277778,482.277778,312.000000,271.000000,328.000000,277.000000,254.000000,280.000000,...,577.000000,546.000000,542.000000,524.000000,568.000000,519.000000,654.000000,695.000000,795.000000,536.000000
3,American Samoa,3.000000,4.000000,6.000000,4.000000,1.000000,3.000000,2.000000,5.000000,5.000000,...,3.000000,4.000000,0.000000,7.000000,13.000000,0.000000,3.823529,3.823529,3.823529,3.823529
4,Andorra,0.454545,1.000000,0.454545,0.454545,0.000000,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.454545,0.454545,0.454545,0.454545,2.000000,0.454545,0.454545,0.454545
5,Angola,1180.500000,1180.500000,1180.500000,1180.500000,1180.500000,1180.500000,1180.500000,1180.500000,1055.000000,...,1180.500000,1254.000000,1196.000000,1180.500000,1180.500000,1180.500000,1180.500000,1180.500000,1180.500000,1180.500000
6,Anguilla,2.000000,1.000000,0.000000,5.000000,4.000000,1.000000,1.000000,0.000000,0.000000,...,4.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
7,Antigua and Barbuda,5.000000,4.000000,3.000000,11.000000,17.000000,16.000000,16.000000,6.000000,10.533333,...,10.533333,10.533333,10.533333,20.000000,12.000000,3.000000,9.000000,16.000000,10.000000,10.533333
8,Argentina,2967.000000,2338.000000,2198.000000,2111.000000,2139.000000,2371.000000,2642.000000,2384.000000,2511.000000,...,3228.000000,2837.000000,2625.000000,2317.000000,2384.000000,2308.000000,2418.000000,2094.000000,1961.000000,2477.650000
9,Armenia,71.444444,83.000000,58.000000,79.000000,77.000000,97.000000,97.000000,56.000000,71.000000,...,72.000000,75.000000,87.000000,70.000000,50.000000,73.000000,52.000000,61.000000,71.444444,71.444444
10,Aruba,4.000000,2.000000,6.000000,5.000000,3.000000,5.000000,4.000000,4.000000,2.000000,...,2.000000,3.916667,3.916667,3.916667,3.916667,3.916667,3.916667,3.916667,3.916667,3.916667
11,Australia,302.000000,263.000000,259.000000,281.000000,255.000000,261.000000,263.000000,231.000000,248.000000,...,243.000000,236.000000,227.000000,208.000000,221.000000,225.000000,221.000000,193.000000,220.000000,226.000000
12,Austria,50.000000,59.000000,54.000000,61.000000,45.000000,58.000000,51.000000,61.000000,77.000000,...,42.000000,44.000000,54.000000,70.000000,86.000000,77.000000,65.000000,65.000000,79.000000,80.000000
13,Azerbaijan,203.733333,203.733333,203.733333,203.733333,189.000000,192.000000,203.733333,206.000000,211.000000,...,236.000000,211.000000,169.000000,182.000000,197.000000,168.000000,230.000000,197.000000,245.000000,203.733333
14,Bahamas,50.000000,44.000000,52.000000,61.000000,78.000000,73.000000,87.000000,94.000000,127.000000,...,122.000000,146.000000,111.000000,122.000000,91.000000,95.000000,73.000000,119.000000,128.000000,95.100000
15,Bahrain,5.750000,5.750000,5.750000,5.750000,4.000000,6.000000,13.000000,2.000000,12.000000,...,9.000000,3.000000,4.000000,6.000000,5.000000,4.000000,0.000000,1.000000,3.000000,5.750000
16,Bangladesh,3471.000000,3902.000000,3592.000000,4166.000000,3863.000000,4099.000000,4219.000000,3988.000000,3966.000000,...,4514.000000,4035.000000,3591.000000,3549.000000,3830.000000,3955.750000,3955.750000,3955.750000,3955.750000,3955.750000
17,Barbados,33.000000,22.000000,29.000000,35.000000,25.000000,23.000000,19.000000,31.000000,27.000000,...,25.000000,31.000000,22.000000,30.000000,28.000000,48.000000,41.000000,32.000000,43.000000,29.500000
18,Belarus,369.153846,369.153846,369.153846,369.153846,649.000000,552.000000,487.000000,401.000000,373.000000,...,340.000000,326.000000,307.000000,240.000000,226.000000,225.000000,369.153846,369.153846,369.153846,369.153846
19,Belgium,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,...,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000
20,Belize,67.000000,79.000000,81.000000,92.000000,97.000000,103.000000,97.000000,129.000000,124.000000,...,123.000000,119.000000,138.000000,142.000000,143.000000,134.000000,102.000000,125.000000,113.000000,112.600000
21,Bermuda,2.000000,1.000000,2.000000,3.000000,3.000000,5.000000,6.000000,7.000000,8.000000,...,4.000000,4.000000,8.000000,5.000000,5.000000,0.000000,7.000000,7.000000,9.000000,4.000000
22,Bhutan,5.000000,15.000000,11.000000,9.000000,14.000000,18.000000,16.000000,16.000000,32.000000,...,15.470588,12.000000,9.000000,13.000000,9.000000,8.000000,19.000000,15.470588,15.470588,15.470588
23,Bolivia (Plurinational State of),541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,541.000000,...,541.000000,543.000000,642.000000,747.000000,574.000000,497.000000,428.000000,418.000000,485.000000,535.000000
24,Bosnia and Herzegovina,50.611111,68.000000,50.611111,50.611111,66.000000,66.000000,71.000000,56.000000,51.000000,...,50.000000,57.000000,45.000000,42.000000,39.000000,42.000000,43.000000,32.000000,35.000000,39.000000
25,Botswana,312.000000,259.000000,291.000000,261.000000,280.000000,281.000000,289.000000,303.000000,277.000000,...,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,221.000000,273.000000,277.000000,277.000000
26,Brazil,51064.000000,48394.000000,47593.000000,49165.000000,47731.000000,50135.000000,51461.000000,52289.000000,52233.000000,...,59733.000000,58184.000000,61208.000000,63788.000000,55980.000000,44073.000000,47722.000000,45562.000000,44367.000000,52195.750000
27,British Virgin Islands,2.000000,4.000000,2.666667,2.000000,2.666667,2.666667,2.666667,2.666667,2.666667,...,2.666667,2.666667,2.666667,2.666667,2.666667,2.666667,2.666667,2.666667,2.666667,2.666667
28,Brunei Darussalam,3.000000,2.000000,2.000000,3.000000,3.000000,1.000000,3.000000,1.000000,1.000000,...,2.272727,2.272727,2.272727,2.272727,2.272727,2.272727,2.272727,2.272727,2.272727,2.272727
29,Bulgaria,247.000000,244.000000,199.000000,186.000000,177.000000,172.000000,150.000000,148.000000,128.000000,...,112.000000,126.000000,79.000000,103.000000,92.000000,83.000000,69.000000,89.000000,76.000000,74.000000
30,Burundi,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,...,564.000000,461.000000,635.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
31,Cabo Verde,15.000000,21.000000,44.000000,35.000000,40.000000,40.000000,40.000000,40.000000,40.000000,...,65.000000,46.000000,62.000000,38.000000,31.000000,33.000000,36.000000,40.000000,40.000000,40.000000
32,Cambodia,509.000000,511.000000,448.000000,400.000000,393.000000,333.000000,331.000000,331.000000,268.000000,...,391.555556,391.555556,391.555556,391.555556,391.555556,391.555556,391.555556,391.555556,391.555556,391.555556
33,Cameroon,1002.000000,962.300000,962.300000,962.300000,962.300000,776.000000,1277.000000,999.000000,835.000000,...,962.300000,861.000000,787.000000,1004.000000,962.300000,962.300000,1202.000000,962.300000,962.300000,962.300000
34,Canada,549.000000,625.000000,664.000000,608.000000,597.000000,614.000000,610.000000,557.000000,609.000000,...,525.000000,611.000000,616.000000,665.000000,662.000000,689.000000,764.000000,796.000000,874.000000,634.650000
35,Cayman Islands,3.000000,5.000000,3.000000,1.000000,2.000000,4.000000,8.000000,9.000000,4.285714,...,5.000000,4.285714,4.285714,3.000000,7.000000,2.000000,3.000000,4.285714,4.285714,4.285714
36,Chile,513.000000,685.684211,576.000000,590.000000,616.000000,588.000000,630.000000,541.000000,636.000000,...,438.000000,419.000000,620.000000,779.000000,825.000000,924.000000,1115.000000,906.000000,1322.000000,685.684211
37,China,24393.000000,24711.000000,20770.000000,17973.000000,16119.000000,14811.000000,14667.000000,13410.000000,12015.000000,...,10083.000000,9200.000000,8634.000000,7990.000000,7525.000000,7379.000000,7157.000000,13264.611111,13264.611111,13264.611111
38,"China, Hong Kong Special Administrative Region",52.000000,45.000000,34.000000,35.000000,18.000000,36.000000,47.000000,35.000000,17.000000,...,27.000000,22.000000,28.000000,24.000000,48.000000,24.000000,22.000000,23.000000,30.000000,32.800000
39,"China, Macao Special Administrative Region",8.000000,4.000000,4.000000,10.000000,6.000000,4.000000,5.000000,2.000000,4.000000,...,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,4.000000
40,Colombia,23523.000000,20210.000000,18111.000000,17479.000000,17198.000000,16140.000000,15817.000000,15459.000000,16127.000000,...,13343.000000,12783.000000,12402.000000,12298.000000,11678.000000,11678.000000,11508.000000,13144.000000,13097.000000,15192.850000
41,Cook Islands,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,...,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095,0.628095
42,Costa Rica,300.000000,280.000000,335.000000,351.000000,369.000000,512.000000,525.000000,527.000000,474.000000,...,477.000000,557.000000,578.000000,603.000000,585.000000,563.000000,570.000000,588.000000,656.000000,906.000000
43,Croatia,69.000000,83.000000,68.000000,74.000000,62.000000,71.000000,49.000000,62.000000,49.000000,...,36.000000,37.000000,44.000000,46.000000,24.000000,33.000000,40.000000,33.000000,31.000000,50.400000
44,Cuba,642.000000,660.000000,684.000000,576.000000,568.000000,515.000000,565.000000,505.000000,534.000000,...,600.000000,619.000000,572.000000,516.000000,491.000000,500.000000,578.941176,578.941176,578.941176,578.941176
45,Curaçao,43.000000,41.000000,26.000000,18.000000,26.000000,30.800000,30.800000,30.800000,30.800000,...,30.800000,30.800000,30.800000,30.800000,30.800000,30.800000,30.800000,30.800000,30.800000,30.800000
46,Cyprus,13.450000,16.000000,20.000000,15.000000,13.000000,9.000000,19.000000,8.000000,9.000000,...,11.000000,15.000000,13.000000,7.000000,15.000000,15.000000,15.000000,16.000000,8.000000,11.000000
47,Czechia,163.000000,134.000000,108.000000,130.000000,126.000000,114.000000,94.000000,103.000000,86.000000,...,81.000000,88.000000,65.000000,66.000000,96.250000,91.000000,64.000000,46.000000,88.000000,83.000000
48,Denmark,53.615385,53.615385,53.615385,53.615385,53.615385,53.615385,53.615385,42.000000,46.000000,...,74.000000,62.000000,56.000000,71.000000,58.000000,50.000000,48.000000,37.000000,58.000000,53.615385
49,Dominica,8.000000,8.000000,8.000000,5.000000,7.000000,7.000000,13.000000,15.000000,6.000000,...,9.000000,9.000000,16.000000,19.000000,13.000000,13.000000,15.000000,10.000000,19.000000,11.111111

In [90]:
pivot_df.to_csv('global_intentional_homicide_count.csv',index=False)