In [18]:
import pandas as pd  
import os

In [19]:
csv_path = os.path.join('..', 'Web Scrapping', 'raw_ghi_data.csv')

# Read the CSV file
ghi_df = pd.read_csv(csv_path)  # Using pandas

In [20]:
ghi_df.head(50)

    Year  Rank               Country  Health Index
0   2012     1                 Japan          96.1
1   2012     2             Indonesia          94.1
2   2012     3             Sri Lanka          93.5
3   2012     4              Thailand          92.6
4   2012     5                Israel          91.7
5   2012     6               Denmark          89.8
6   2012     7              Colombia          88.9
7   2012     8                 Malta          87.0
8   2012     9           New Zealand          86.8
9   2012    10                Sweden          86.8
10  2012    11               Austria          83.2
11  2012    12              Slovenia          82.9
12  2012    13                Panama          82.4
13  2012    14               Belgium          82.2
14  2012    15                France          80.7
15  2012    16                Mexico          80.1
16  2012    17           Switzerland          79.5
17  2012    18               Bolivia          79.2
18  2012    19             Australia          79.1
19  2012    20                Norway          79.0
20  2012    21               Ecuador          77.8
21  2012    22               Finland          77.1
22  2012    23             Argentina          76.7
23  2012    24           Philippines          76.1
24  2012    25        United Kingdom          76.0
25  2012    26                Taiwan          74.1
26  2012    27                Canada          72.0
27  2012    28               Germany          72.0
28  2012    29                Jordan          70.8
29  2012    30              Slovakia          70.4
30  2012    31           Netherlands          70.4
31  2012    32                Turkey          70.0
32  2012    33              Portugal          70.0
33  2012    34                 Spain          69.9
34  2012    35               Estonia          69.4
35  2012    36              Malaysia          69.1
36  2012    37                 Italy          67.8
37  2012    38               Georgia          67.1
38  2012    39                 Egypt          65.7
39  2012    40         United States          65.5
40  2012    41               Croatia          65.0
41  2012    42        Czech Republic          65.0
42  2012    43             Lithuania          64.6
43  2012    44  United Arab Emirates          63.9
44  2012    45              Pakistan          60.4
45  2012    46              Bulgaria          60.3
46  2012    47               Hungary          60.0
47  2012    48          South Africa          59.5
48  2012    49                 India          59.4
49  2012    50                 Chile          59.3

In [21]:
ghi_df.drop('Rank',axis=1,inplace=True)

In [22]:
ghi_df.isna().sum() # check any null values

Year            0
Country         0
Health Index    0
dtype: int64

In [23]:
print(len(ghi_df['Year'].unique())) # total unique year value
print(ghi_df['Year'].max()) #max year
print(ghi_df['Year'].min()) #min year
print(ghi_df['Year'].max()-ghi_df['Year'].min()+1) #looks like all years from 1990 to 2021 exist

12
2023
2012
12

In [24]:
all_years = range(2013, 2025)  # 2021 inclusive

# Create a pivot table with countries as rows and years as columns
pivot_df = (
    ghi_df.pivot_table(
        index='Country',
        columns='Year',
        values='Health Index',
        aggfunc='first'  # Takes the first occurrence if duplicates exist
    )
    .reindex(columns=all_years)  # Ensure all years are present as columns
    .sort_index(axis=0)  # Sort countries alphabetically
    .reset_index()       # Move Country from index to column
)

# Rename the columns to match your requirements
pivot_df.columns.name = None  # Remove the 'Year' label from columns
pivot_df = pivot_df.rename(columns={'Country': 'Country'})

In [25]:
pivot_df.head(50)

,Country,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Albania,44.4,61.4,67.4,NaN,NaN,NaN,NaN,53.0,50.7,50.5,49.6,NaN
1,Algeria,NaN,NaN,57.2,NaN,NaN,NaN,54.1,54.9,55.0,52.9,53.6,NaN
2,Argentina,78.3,76.7,75.2,73.7,73.3,71.3,69.4,69.3,68.6,69.3,68.9,NaN
3,Armenia,NaN,NaN,48.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Australia,75.6,73.6,71.9,73.7,74.2,76.2,76.4,77.4,77.7,78.1,75.3,NaN
5,Austria,81.5,79.7,78.4,77.8,80.9,78.8,79.2,78.7,78.4,76.7,77.2,NaN
6,Azerbaijan,28.7,NaN,23.9,NaN,NaN,NaN,NaN,43.2,44.0,44.8,46.8,NaN
7,Bahrain,NaN,NaN,84.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Bangladesh,NaN,NaN,43.3,NaN,43.5,44.6,40.3,42.8,42.7,42.3,42.3,NaN
9,Belarus,NaN,48.0,45.4,NaN,53.8,NaN,58.0,59.0,44.4,45.6,47.1,NaN
10,Belgium,81.5,78.0,77.9,78.1,78.9,80.4,79.4,74.3,75.2,75.5,75.2,NaN
11,Bolivia,67.4,51.5,49.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Bosnia And Herzegovina,54.5,54.4,52.1,60.5,61.5,55.9,53.2,52.3,53.5,54.3,54.9,NaN
13,Brazil,57.6,53.7,52.2,51.1,51.7,52.7,54.6,56.3,57.3,57.8,58.2,NaN
14,Bulgaria,54.6,58.0,58.5,50.9,54.0,52.1,54.0,55.4,56.1,56.4,56.7,NaN
15,Cambodia,53.8,53.8,54.2,NaN,NaN,NaN,NaN,NaN,NaN,49.4,NaN,NaN
16,Canada,72.8,71.9,69.6,68.6,69.2,70.6,71.0,71.6,71.8,71.3,70.4,NaN
17,Chile,61.5,58.7,58.5,61.1,61.0,61.9,65.5,65.4,63.7,64.0,64.4,NaN
18,China,60.9,65.1,58.7,61.2,62.2,62.9,64.0,64.5,66.4,66.4,67.5,NaN
19,Colombia,77.3,68.5,68.9,73.2,65.8,67.8,67.5,67.2,66.7,67.2,67.9,NaN
20,Costa Rica,77.1,63.9,62.0,NaN,60.2,NaN,62.6,62.4,62.9,62.7,63.1,NaN
21,Croatia,50.0,55.9,57.3,60.0,65.5,63.8,64.1,62.7,64.2,64.1,63.9,NaN
22,Cuba,NaN,NaN,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Cyprus,70.0,68.7,78.4,72.9,54.2,55.1,50.2,51.8,52.7,52.0,54.7,NaN
24,Czech Republic,62.0,66.3,67.2,72.3,74.1,75.4,74.7,74.6,75.4,75.3,75.5,NaN
25,Denmark,86.1,85.6,79.3,81.9,75.4,77.1,79.4,80.0,80.0,80.1,79.2,NaN
26,Dominican Republic,NaN,NaN,78.7,NaN,NaN,NaN,NaN,54.7,55.0,55.5,55.5,NaN
27,Ecuador,64.8,59.4,63.1,65.7,69.2,NaN,72.5,70.6,68.8,69.3,69.5,NaN
28,Egypt,59.1,61.3,54.7,46.6,43.7,44.4,44.2,45.8,46.2,47.0,47.6,NaN
29,Estonia,78.1,76.3,73.1,69.9,71.3,71.3,72.1,72.7,72.8,73.3,74.1,NaN
30,Finland,76.4,68.7,69.4,74.4,74.8,75.4,73.5,75.8,76.4,76.3,77.1,NaN
31,France,85.6,82.3,82.6,82.2,78.6,78.0,78.6,80.0,81.0,80.2,79.4,NaN
32,Georgia,69.0,NaN,62.6,NaN,NaN,NaN,51.3,51.2,53.8,54.2,54.8,NaN
33,Germany,73.3,75.3,75.6,75.8,76.7,75.4,74.3,73.3,73.8,73.2,71.9,NaN
34,Greece,50.4,59.0,56.7,59.2,53.9,54.2,55.2,56.2,57.0,57.3,57.5,NaN
35,Guam,NaN,NaN,39.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Guatemala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.8,65.9,65.9,67.5,NaN
37,Honduras,NaN,NaN,16.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Hong Kong,71.1,71.8,80.6,74.3,68.0,63.8,67.3,66.1,66.3,66.3,NaN,NaN
39,Hong Kong (China),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.8,NaN
40,Hungary,51.0,46.6,51.6,52.1,53.5,51.1,48.2,47.8,51.6,53.4,54.4,NaN
41,Iceland,64.8,NaN,58.4,74.3,65.6,65.5,66.4,65.9,65.7,66.4,67.0,NaN
42,India,62.7,64.6,66.9,66.5,69.2,67.4,68.3,67.1,66.2,65.7,65.1,NaN
43,Indonesia,48.5,60.2,66.1,62.6,64.8,66.0,62.0,60.5,60.5,60.4,60.5,NaN
44,Iran,45.7,48.6,50.1,49.8,51.6,51.2,51.2,51.7,52.2,52.3,52.3,NaN
45,Iraq,NaN,28.5,30.0,NaN,45.9,NaN,NaN,41.4,44.6,44.6,43.5,NaN
46,Ireland,49.0,42.6,49.5,50.4,53.3,53.0,48.6,51.9,52.8,52.3,51.8,NaN
47,Israel,87.0,75.4,76.4,76.1,74.8,74.1,73.4,73.3,73.8,73.8,73.5,NaN
48,Italy,64.8,65.0,65.8,67.8,66.3,68.0,67.1,66.6,66.8,66.8,66.3,NaN
49,Japan,80.1,85.0,87.1,80.4,78.6,81.7,80.4,81.1,80.7,80.5,80.3,NaN

In [26]:
# Fill NaN values with the respective country's mean
pivot_df = pivot_df.set_index("Country").apply(lambda row: row.fillna(row.mean()), axis=1).reset_index()

In [27]:
pivot_df.to_csv('global_health_index.csv',index=False)