In [2]:
import pandas as pd  
import os

In [3]:
csv_path = os.path.join('..', 'Web Scrapping', 'raw_gci_data.csv')

# Read the CSV file
gci_df = pd.read_csv(csv_path)  # Using pandas

In [4]:
gci_df.head(50)

    Year  Rank                 Country  Crime Index
0   2012     1               Venezuela         84.7
1   2012     2            South Africa         78.1
2   2012     3             Puerto Rico         73.1
3   2012     4                Malaysia         70.9
4   2012     5           United States         64.9
5   2012     6                 Algeria         64.8
6   2012     7                  Mexico         62.5
7   2012     8                    Peru         60.9
8   2012     9                 Lebanon         59.9
9   2012    10              Bangladesh         59.7
10  2012    11                  Brazil         59.3
11  2012    12                Pakistan         58.7
12  2012    13                   Italy         56.7
13  2012    14                   Chile         56.4
14  2012    15                 Ecuador         55.4
15  2012    16                 Ukraine         55.4
16  2012    17             Philippines         53.1
17  2012    18                  Greece         52.0
18  2012    19                    Iran         51.9
19  2012    20                  Russia         50.6
20  2012    21               Argentina         48.4
21  2012    22                Colombia         47.2
22  2012    23                Slovakia         46.9
23  2012    24             New Zealand         46.8
24  2012    25                 Ireland         46.1
25  2012    26          United Kingdom         46.0
26  2012    27                   India         45.6
27  2012    28                 Denmark         45.3
28  2012    29                  France         44.8
29  2012    30                   China         44.5
30  2012    31                   Egypt         44.3
31  2012    32                 Austria         44.1
32  2012    33                 Uruguay         42.8
33  2012    34                Bulgaria         41.4
34  2012    35                  Israel         40.8
35  2012    36                Portugal         40.6
36  2012    37                 Belgium         40.6
37  2012    38               Australia         40.6
38  2012    39  Bosnia And Herzegovina         40.3
39  2012    40                  Canada         39.8
40  2012    41                Thailand         39.7
41  2012    42               Lithuania         39.1
42  2012    43                  Poland         38.7
43  2012    44              Azerbaijan         38.5
44  2012    45                 Jamaica         36.7
45  2012    46          Czech Republic         36.6
46  2012    47                  Sweden         36.2
47  2012    48    United Arab Emirates         35.9
48  2012    49                Slovenia         35.7
49  2012    50                 Morocco         33.6

In [5]:
gci_df.drop('Rank',axis=1,inplace=True)

In [6]:
gci_df.isna().sum() # check any null values

Year           0
Country        0
Crime Index    0
dtype: int64

In [8]:
print(len(gci_df['Year'].unique())) # total unique year value
print(gci_df['Year'].max()) #max year
print(gci_df['Year'].min()) #min year
print(gci_df['Year'].max()-gci_df['Year'].min()+1) #looks like all years from 1990 to 2021 exist

12
2023
2012
12

In [9]:
all_years = range(2012, 2024)  # 2021 inclusive

# Create a pivot table with countries as rows and years as columns
pivot_df = (
    gci_df.pivot_table(
        index='Country',
        columns='Year',
        values='Crime Index',
        aggfunc='first'  # Takes the first occurrence if duplicates exist
    )
    .reindex(columns=all_years)  # Ensure all years are present as columns
    .sort_index(axis=0)  # Sort countries alphabetically
    .reset_index()       # Move Country from index to column
)

# Rename the columns to match your requirements
pivot_df.columns.name = None  # Remove the 'Year' label from columns
pivot_df = pivot_df.rename(columns={'Country': 'Country'})

In [10]:
pivot_df.head(50)

,Country,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,NaN,NaN,82.5,77.3,NaN,73.9,NaN,76.6,76.2,76.4,77.0,78.6
1,Albania,30.1,47.0,51.3,49.6,48.2,44.3,39.9,40.3,39.5,41.6,46.1,45.7
2,Algeria,64.8,51.8,52.3,51.3,57.6,49.6,50.7,48.3,49.8,51.9,53.8,52.6
3,Angola,NaN,52.3,63.0,68.0,NaN,65.5,NaN,NaN,65.0,66.6,66.4,65.4
4,Argentina,48.4,59.3,57.5,62.4,63.3,62.6,61.8,62.6,61.8,63.3,64.1,64.3
5,Armenia,NaN,41.1,35.0,29.1,31.1,27.1,28.3,22.0,21.6,23.3,22.1,22.0
6,Australia,40.6,44.4,41.2,42.2,43.1,42.4,42.5,42.8,41.4,42.4,43.8,45.5
7,Austria,44.1,30.4,25.8,26.2,24.1,19.2,20.4,21.4,23.7,25.2,26.1,27.3
8,Azerbaijan,38.5,36.7,34.2,35.5,32.4,27.1,30.5,31.7,31.6,31.7,32.3,31.8
9,Bahamas,NaN,NaN,NaN,72.9,NaN,63.2,NaN,NaN,62.9,62.3,62.5,62.4
10,Bahrain,NaN,19.8,20.5,40.0,37.3,35.3,37.0,32.9,29.3,26.1,24.4,24.0
11,Bangladesh,59.7,59.4,62.2,64.2,68.6,67.2,68.5,65.8,63.9,64.2,63.4,62.6
12,Barbados,NaN,NaN,44.4,44.4,NaN,NaN,NaN,NaN,NaN,NaN,46.6,47.9
13,Belarus,NaN,26.8,32.9,30.5,27.6,22.3,26.6,23.5,25.0,60.3,58.4,56.4
14,Belgium,40.6,42.9,41.5,42.0,45.2,44.5,42.2,42.5,44.0,44.2,45.4,49.1
15,Belize,NaN,NaN,NaN,62.3,NaN,NaN,NaN,NaN,NaN,51.3,51.5,53.1
16,Bermuda,NaN,NaN,NaN,40.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Bolivia,NaN,46.4,69.0,65.6,56.6,59.5,52.9,53.3,52.9,55.4,58.3,60.8
18,Bosnia And Herzegovina,40.3,43.3,45.0,45.8,42.5,41.0,40.1,43.8,43.0,43.0,42.2,42.9
19,Botswana,NaN,NaN,47.0,46.8,NaN,58.2,NaN,NaN,53.5,52.8,52.4,53.7
20,Brazil,59.3,62.6,67.0,69.0,71.2,70.6,70.6,70.2,68.9,67.8,67.0,66.6
21,Brunei,NaN,30.1,31.5,30.4,37.0,36.1,NaN,NaN,27.7,28.0,29.0,29.0
22,Bulgaria,41.4,41.5,40.0,43.5,41.4,40.2,39.7,40.0,38.5,38.1,38.7,38.0
23,Cambodia,NaN,32.8,40.8,44.1,48.2,54.6,54.4,51.3,50.7,51.2,50.7,52.9
24,Cameroon,NaN,NaN,NaN,64.8,NaN,NaN,NaN,NaN,NaN,NaN,66.6,64.8
25,Canada,39.8,35.0,36.3,37.5,39.2,39.2,39.3,39.5,39.7,41.2,42.9,44.3
26,Chile,56.4,40.3,47.1,45.0,42.0,47.5,46.5,46.8,45.2,52.1,54.0,58.1
27,China,44.5,26.9,30.1,41.7,32.1,33.9,39.4,45.5,31.8,30.2,29.4,26.3
28,Colombia,47.2,54.2,58.5,56.9,48.5,51.7,50.7,51.3,54.8,55.8,57.7,60.2
29,Costa Rica,NaN,66.7,61.4,63.0,57.6,55.9,53.9,56.1,56.3,55.3,53.9,53.8
30,Croatia,32.4,32.3,28.9,29.3,29.5,27.8,27.0,24.7,24.7,24.9,24.1,24.6
31,Cuba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.5,29.1,30.9,31.6
32,Cyprus,30.3,34.0,37.6,31.6,30.2,32.5,30.2,29.3,30.0,32.0,32.1,31.4
33,Czech Republic,36.6,34.1,33.9,32.9,32.1,30.2,28.8,26.7,25.5,25.3,25.5,26.6
34,Denmark,45.3,30.7,29.3,25.7,25.7,21.1,22.0,24.2,25.1,26.7,26.6,26.6
35,Dominican Republic,NaN,58.1,66.4,67.7,63.2,62.6,61.5,61.4,61.2,60.1,60.9,61.2
36,Ecuador,55.4,59.7,60.0,54.0,52.9,50.9,49.2,49.0,50.9,54.4,57.2,59.4
37,Egypt,44.3,48.7,52.4,60.1,56.5,52.9,53.7,50.7,46.9,46.8,46.6,47.2
38,El Salvador,NaN,50.6,64.3,69.4,72.0,71.6,69.7,68.1,68.0,68.8,68.6,64.4
39,Eritrea,NaN,57.8,39.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Estonia,25.0,24.2,29.1,28.1,24.7,23.0,20.8,20.8,23.1,23.4,23.8,25.1
41,Ethiopia,NaN,26.0,36.1,35.1,34.2,49.2,47.7,47.2,49.2,50.0,50.1,50.9
42,Faroe Islands,NaN,NaN,NaN,18.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Fiji,NaN,NaN,39.0,49.4,NaN,55.6,NaN,NaN,58.9,57.9,55.6,57.0
44,Finland,17.6,32.7,29.2,29.5,28.1,24.6,23.7,22.8,23.3,27.0,27.3,26.8
45,France,44.8,51.1,47.3,49.7,44.1,43.7,45.3,46.4,46.8,49.2,52.4,55.3
46,Georgia,31.3,19.6,19.9,22.0,22.2,20.8,20.3,19.9,20.2,22.6,24.3,25.9
47,Germany,21.2,23.9,27.1,28.5,33.0,32.0,36.7,34.5,34.8,35.4,36.4,37.6
48,Ghana,NaN,NaN,46.4,49.4,49.0,47.0,45.0,51.9,49.0,48.5,46.8,44.5
49,Greece,52.0,49.8,43.0,41.4,38.5,40.3,39.1,38.6,40.3,44.1,47.4,47.0

In [11]:
# Fill NaN values with the respective country's mean
pivot_df = pivot_df.set_index("Country").apply(lambda row: row.fillna(row.mean()), axis=1).reset_index()

In [12]:
pivot_df.to_csv('global_crime_index.csv',index=False)