In [41]:
import pandas as pd  
import os

In [42]:
csv_path = os.path.join('..', 'Web Scrapping', 'data_cts_intentional_homicide.xlsx')

# Read the CSV file
gihr_df = pd.read_excel(csv_path,header=2)  # Using pandas

In [43]:
gihr_df.head(50)

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
0,ARM,Armenia,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,35.0,CTS
1,CHE,Switzerland,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,28.0,CTS
2,COL,Colombia,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,15053.0,CTS
3,CZE,Czechia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,69.0,CTS
4,DEU,Germany,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,455.0,CTS
5,FIN,Finland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,70.0,CTS
6,GTM,Guatemala,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,2764.0,CTS
7,HND,Honduras,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,905.0,CTS
8,HUN,Hungary,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,229.0,CTS
9,ISL,Iceland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,1.0,CTS
10,ITA,Italy,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,864.0,CTS
11,JPN,Japan,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,259.0,CTS
12,LKA,Sri Lanka,Asia,Southern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,809.0,CTS
13,LTU,Lithuania,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,173.0,CTS
14,MNG,Mongolia,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,207.0,CTS
15,NOR,Norway,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,16.0,CTS
16,SRB,Serbia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,134.0,CTS
17,SVK,Slovakia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,53.0,CTS
18,SVN,Slovenia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,16.0,CTS
19,TUR,Türkiye,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2013,Counts,9891.0,CTS
20,ARM,Armenia,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,41.0,CTS
21,CHE,Switzerland,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,26.0,CTS
22,COL,Colombia,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,16476.0,CTS
23,CZE,Czechia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,55.0,CTS
24,DEU,Germany,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,489.0,CTS
25,FIN,Finland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,66.0,CTS
26,GTM,Guatemala,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,2649.0,CTS
27,HND,Honduras,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,1319.0,CTS
28,HUN,Hungary,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,204.0,CTS
29,ISL,Iceland,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,1.0,CTS
30,ITA,Italy,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,806.0,CTS
31,JPN,Japan,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,243.0,CTS
32,LKA,Sri Lanka,Asia,Southern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,902.0,CTS
33,LTU,Lithuania,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,174.0,CTS
34,MNG,Mongolia,Asia,Eastern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,217.0,CTS
35,NOR,Norway,Europe,Northern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,18.0,CTS
36,SRB,Serbia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,117.0,CTS
37,SVK,Slovakia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,47.0,CTS
38,SVN,Slovenia,Europe,Southern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,23.0,CTS
39,TUR,Türkiye,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2014,Counts,10389.0,CTS
40,ARM,Armenia,Asia,Western Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,47.0,CTS
41,ATG,Antigua and Barbuda,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,3.0,CTS
42,AUT,Austria,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,29.0,CTS
43,BEL,Belgium,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,81.0,CTS
44,BLZ,Belize,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,55.0,CTS/MoI
45,BOL,Bolivia (Plurinational State of),Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,330.0,CTS
46,BTN,Bhutan,Asia,Southern Asia,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,21.0,CTS
47,CHE,Switzerland,Europe,Western Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,28.0,CTS
48,COL,Colombia,Americas,Latin America and the Caribbean,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,15819.0,CTS
49,CZE,Czechia,Europe,Eastern Europe,Persons arrested/suspected for intentional hom...,by citizenship,National citizens,Male,Total,2015,Counts,66.0,CTS

In [44]:
gihr_df.columns.tolist()

['Iso3_code',
 'Country',
 'Region',
 'Subregion',
 'Indicator',
 'Dimension',
 'Category',
 'Sex',
 'Age',
 'Year',
 'Unit of measurement',
 'VALUE',
 'Source']

In [45]:
gihr_df.drop(['Iso3_code','Region',
 'Subregion','Source'],axis=1,inplace=True)

We need to filter out values from this dataset

In [46]:
gihr_df['Dimension'].unique()

array(['by citizenship', 'Total', 'by relationship to perpetrator',
       'by situational context', 'by mechanisms', 'by location'],
      dtype=object)

In [47]:
gihr_df=gihr_df[gihr_df['Dimension']=='Total']

In [48]:
gihr_df

,Country,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE
1457,Aruba,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1458,Anguilla,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1459,Armenia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,178.000000
1460,Antigua and Barbuda,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1.000000
1461,Australia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,374.000000
...,...,...,...,...,...,...,...,...,...
118432,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2019,"Rate per 100,000 population",8.677549
118433,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2020,"Rate per 100,000 population",8.479234
118434,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2021,"Rate per 100,000 population",8.769468
118435,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2022,"Rate per 100,000 population",8.424728
118436,World,Victims of Intentional Homicide - Regional Est...,Total,Total,Male,Total,2023,"Rate per 100,000 population",8.249462

In [49]:
gihr_df['Indicator'].unique()

array(['Victims of intentional homicide',
       'Persons arrested/suspected for intentional homicide',
       'Persons convicted for intentional homicide',
       'Death due to intentional homicide in prison',
       'Victims of Intentional Homicide - Regional Estimate'],
      dtype=object)

In [50]:
gihr_df=gihr_df[gihr_df['Indicator']=='Victims of intentional homicide']

In [51]:
gihr_df

,Country,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE
1457,Aruba,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1458,Anguilla,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.000000
1459,Armenia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,178.000000
1460,Antigua and Barbuda,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,1.000000
1461,Australia,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,374.000000
...,...,...,...,...,...,...,...,...,...
106341,Slovenia,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.000000
106342,Türkiye,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.874463
106343,Uruguay,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",1.919872
106344,Holy See,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.000000
106345,Saint Vincent and the Grenadines,Victims of intentional homicide,Total,Total,Female,60 and older,2022,"Rate per 100,000 population",0.000000

In [52]:
gihr_df['Sex'].unique()

array(['Total', 'Male', 'Female'], dtype=object)

In [53]:
gihr_df=gihr_df[gihr_df['Sex']=='Total']

In [54]:
gihr_df['Year'].unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023], dtype=int64)

In [55]:
gihr_df['Unit of measurement'].unique()

array(['Counts', 'Rate per 100,000 population'], dtype=object)

In [56]:
gihr_df=gihr_df[gihr_df['Unit of measurement']=='Rate per 100,000 population']

In [57]:
gihr_df.head(50)

,Country,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE
63365,Aruba,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.000000
63366,Anguilla,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.000000
63367,Armenia,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",5.011081
63368,Antigua and Barbuda,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.585628
63369,Australia,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",2.183776
63370,Austria,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.158911
63371,Azerbaijan,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",4.549806
63372,Belgium,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.040784
63373,Bulgaria,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",2.573006
63374,Bahamas,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",16.307627
63375,Bosnia and Herzegovina,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.640947
63376,Belarus,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",4.987110
63377,Bermuda,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.737363
63378,Brazil,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",19.646343
63379,Barbados,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",13.148659
63380,Bhutan,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",3.393932
63381,Canada,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",2.364207
63382,Switzerland,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.638569
63383,Colombia,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",74.999842
63384,Costa Rica,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",4.452693
63385,Cayman Islands,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",7.692604
63386,Cyprus,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.634236
63387,Germany,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.168014
63388,Denmark,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.797506
63389,Ecuador,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",8.516592
63390,Egypt,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.460643
63391,Spain,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.238220
63392,Estonia,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",7.514471
63393,Finland,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",3.048184
63394,Fiji,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",4.138024
63395,France,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",2.377600
63396,United Kingdom (Scotland),Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.500718
63397,Georgia,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",4.955158
63398,Greece,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.013795
63399,Guyana,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",12.001704
63400,"China, Hong Kong Special Administrative Region",Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",2.463764
63401,Honduras,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",9.949483
63402,Croatia,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",2.833467
63403,Hungary,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",1.936177
63404,India,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",5.105597
63405,Ireland,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.483777
63406,Iraq,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",6.643458
63407,Israel,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",3.234324
63408,Italy,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",3.145633
63409,Jamaica,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",22.858324
63410,Jordan,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",3.313171
63411,Japan,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.547813
63412,Kazakhstan,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",8.598550
63413,Republic of Korea,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",0.471928
63414,Saint Lucia,Victims of intentional homicide,Total,Total,Total,Total,1990,"Rate per 100,000 population",10.155488

In [58]:
gihr_df.columns.tolist()

['Country',
 'Indicator',
 'Dimension',
 'Category',
 'Sex',
 'Age',
 'Year',
 'Unit of measurement',
 'VALUE']

In [59]:
gihr_df.drop(['Indicator',
 'Dimension',
 'Category',
 'Sex',
 'Age', 'Unit of measurement'],axis=1,inplace=True)

In [60]:
gihr_df.head(50)

                                              Country  Year      VALUE
63365                                           Aruba  1990   0.000000
63366                                        Anguilla  1990   0.000000
63367                                         Armenia  1990   5.011081
63368                             Antigua and Barbuda  1990   1.585628
63369                                       Australia  1990   2.183776
63370                                         Austria  1990   1.158911
63371                                      Azerbaijan  1990   4.549806
63372                                         Belgium  1990   1.040784
63373                                        Bulgaria  1990   2.573006
63374                                         Bahamas  1990  16.307627
63375                          Bosnia and Herzegovina  1990   1.640947
63376                                         Belarus  1990   4.987110
63377                                         Bermuda  1990   1.737363
63378                                          Brazil  1990  19.646343
63379                                        Barbados  1990  13.148659
63380                                          Bhutan  1990   3.393932
63381                                          Canada  1990   2.364207
63382                                     Switzerland  1990   1.638569
63383                                        Colombia  1990  74.999842
63384                                      Costa Rica  1990   4.452693
63385                                  Cayman Islands  1990   7.692604
63386                                          Cyprus  1990   0.634236
63387                                         Germany  1990   1.168014
63388                                         Denmark  1990   0.797506
63389                                         Ecuador  1990   8.516592
63390                                           Egypt  1990   0.460643
63391                                           Spain  1990   1.238220
63392                                         Estonia  1990   7.514471
63393                                         Finland  1990   3.048184
63394                                            Fiji  1990   4.138024
63395                                          France  1990   2.377600
63396                       United Kingdom (Scotland)  1990   1.500718
63397                                         Georgia  1990   4.955158
63398                                          Greece  1990   1.013795
63399                                          Guyana  1990  12.001704
63400  China, Hong Kong Special Administrative Region  1990   2.463764
63401                                        Honduras  1990   9.949483
63402                                         Croatia  1990   2.833467
63403                                         Hungary  1990   1.936177
63404                                           India  1990   5.105597
63405                                         Ireland  1990   0.483777
63406                                            Iraq  1990   6.643458
63407                                          Israel  1990   3.234324
63408                                           Italy  1990   3.145633
63409                                         Jamaica  1990  22.858324
63410                                          Jordan  1990   3.313171
63411                                           Japan  1990   0.547813
63412                                      Kazakhstan  1990   8.598550
63413                               Republic of Korea  1990   0.471928
63414                                     Saint Lucia  1990  10.155488

In [61]:
all_years = range(1990, 2024)  # 2021 inclusive

# Create a pivot table with countries as rows and years as columns
pivot_df = (
    gihr_df.pivot_table(
        index='Country',
        columns='Year',
        values='VALUE',
        aggfunc='first'  # Takes the first occurrence if duplicates exist
    )
    .reindex(columns=all_years)  # Ensure all years are present as columns
    .sort_index(axis=0)  # Sort countries alphabetically
    .reset_index()       # Move Country from index to column
)

# Rename the columns to match your requirements
pivot_df.columns.name = None  # Remove the 'Year' label from columns
pivot_df = pivot_df.rename(columns={'Country': 'Country'})

In [62]:
pivot_df.head(50)

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.952186,6.679997,6.792021,6.733248,7.163967,6.578109,4.032458,NaN,NaN
1,Albania,NaN,NaN,3.960395,5.827036,3.425695,7.948279,8.380375,41.304664,20.559899,...,4.614723,2.207938,2.726144,2.001213,2.280398,2.253026,2.123990,2.316086,1.697548,1.387083
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.471750,1.364334,1.326782,1.256917,1.336312,1.198765,1.484943,1.552688,1.748121,1.161072
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.611043,7.564583,0.000000,13.569573,25.536011,0.000000,NaN,NaN,NaN,NaN
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,2.584647,NaN,NaN,NaN
5,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.453473,4.098267,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Anguilla,0.000000,11.490951,0.000000,10.836584,0.000000,10.294420,0.000000,9.752767,0.000000,...,29.136468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Antigua and Barbuda,1.585628,4.732832,3.105373,6.098770,7.480271,10.265661,4.309633,1.407400,NaN,...,NaN,NaN,NaN,22.107264,13.197545,3.283587,9.799011,17.325580,10.771219,NaN
8,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.502777,6.525287,5.979456,5.231560,5.338722,5.131915,5.350509,4.621264,4.318631,NaN
9,Armenia,5.011081,5.146685,8.538965,7.760620,4.666217,3.507094,3.476950,3.080440,2.898640,...,2.463710,2.567458,2.980685,2.401402,1.718234,2.513799,1.798752,2.125177,NaN,NaN
10,Aruba,0.000000,NaN,NaN,NaN,NaN,7.903264,NaN,NaN,NaN,...,1.934751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Australia,2.183776,1.959294,1.715169,1.878924,1.787966,1.967357,1.933865,1.967045,1.785932,...,1.029853,0.985468,0.933006,0.841048,0.879787,0.882951,0.858459,0.743554,0.839663,0.854406
12,Austria,1.158911,1.327809,1.236817,1.011698,1.108570,0.981092,1.243576,0.828126,0.965098,...,0.491353,0.509021,0.617996,0.795565,0.972669,0.867032,0.728585,0.724876,0.871515,0.876191
13,Azerbaijan,4.549806,4.880845,7.615673,6.369838,6.558116,5.738876,5.107916,3.578529,3.488747,...,2.450385,2.163470,1.712532,1.825749,1.962194,1.661643,2.258948,1.924886,2.379726,NaN
14,Bahamas,16.307627,9.973961,14.339324,12.013476,17.537410,13.268715,16.652082,14.795588,NaN,...,31.912278,37.887979,28.604156,31.243198,23.171873,24.070468,18.440746,30.022227,32.198139,NaN
15,Bahrain,NaN,NaN,NaN,NaN,NaN,0.842855,1.314507,0.961531,NaN,...,0.685533,0.219034,0.279798,0.404860,0.333862,0.269239,0.000000,0.066588,0.195636,NaN
16,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.857596,2.531635,2.233043,2.188226,2.342177,NaN,NaN,NaN,NaN,NaN
17,Barbados,13.148659,8.096464,8.452874,8.045145,7.644661,6.487572,NaN,NaN,7.620906,...,8.981563,11.111509,7.868454,10.707746,9.974689,17.069246,14.554594,11.341626,15.231052,NaN
18,Belarus,4.987110,4.561556,5.813520,7.381861,8.103469,9.414106,9.543461,10.086577,10.277188,...,3.589259,3.436175,3.231898,2.527436,2.383958,2.384632,NaN,NaN,NaN,NaN
19,Belgium,1.040784,1.022429,1.203971,1.434903,1.186239,1.400772,1.181455,1.424157,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.080302,NaN,NaN
20,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.251381,33.395728,37.838801,38.049150,37.609162,34.730457,26.099539,31.617834,28.058292,NaN
21,Bermuda,1.737363,5.173841,1.712109,5.100696,10.136162,NaN,6.687509,3.323529,0.000000,...,6.296337,6.302835,12.608651,7.864294,7.833185,0.000000,10.872604,10.827868,13.899936,6.182571
22,Bhutan,3.393932,2.000722,4.673107,3.425445,3.606869,2.919767,2.186655,1.252916,1.931739,...,NaN,1.620268,1.203424,1.723373,1.184586,1.045992,2.467513,NaN,NaN,NaN
23,Bolivia (Plurinational State of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.929773,5.742387,6.584638,4.987675,4.258278,3.622115,3.501612,4.015847,4.369430
24,Bosnia and Herzegovina,1.640947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.402592,1.619990,1.295709,1.224960,1.151461,1.255405,1.303287,0.986161,1.092111,1.224462
25,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9.341080,11.368177,NaN,NaN
26,Brazil,19.646343,18.552388,16.831520,17.865893,18.743233,21.022089,23.686599,24.304930,24.799057,...,29.853793,28.850302,30.119362,31.161176,27.160615,21.244560,22.870606,21.742752,21.096361,NaN
27,British Virgin Islands,6.367602,0.000000,0.000000,0.000000,0.000000,11.211077,10.937030,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,NaN,3.017345,2.620017,1.280469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Bulgaria,2.573006,4.312428,5.397763,5.787493,5.845370,5.910806,5.282583,4.843557,4.681628,...,1.550506,1.755482,1.108393,1.455700,1.309656,1.189884,0.995147,1.294127,1.113412,1.088907
30,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.222326,4.172860,5.649742,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Cabo Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.687247,8.977475,12.096275,7.408953,6.038000,6.418935,6.994644,NaN,NaN,NaN
32,Cambodia,NaN,NaN,5.287755,6.951874,3.279518,3.962670,5.017929,2.739612,6.576453,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.782385,3.355481,4.161037,NaN,NaN,4.585938,NaN,NaN,NaN
34,Canada,2.364207,2.677827,2.571924,2.171301,2.044781,1.992591,2.129861,1.949494,1.843062,...,1.473301,1.699005,1.694480,1.806648,1.775037,1.823575,2.001472,2.070003,2.251344,NaN
35,Cayman Islands,7.692604,7.327484,3.493938,6.672004,6.379178,6.108176,2.928858,5.626987,2.708449,...,8.311101,NaN,NaN,4.648604,10.615631,2.970576,4.367798,NaN,NaN,NaN
36,Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.451832,2.321635,3.394057,4.197454,4.366653,4.813066,5.756139,4.656581,6.761098,NaN
37,China,NaN,NaN,NaN,NaN,NaN,2.242049,2.064349,2.100489,NaN,...,0.726466,0.658962,0.614934,0.565722,0.530300,0.518363,0.501856,NaN,NaN,NaN
38,"China, Hong Kong Special Administrative Region",2.463764,1.634656,1.875144,1.457007,1.588809,1.181784,1.221744,1.589609,0.981394,...,0.368878,0.298653,0.377969,0.322369,0.642468,0.320606,0.293716,0.307298,0.401826,NaN
39,"China, Macao Special Administrative Region",NaN,3.312469,0.805913,3.146910,3.332295,2.006556,4.176612,7.227714,5.676309,...,0.163853,0.160725,0.157651,0.309332,0.303595,0.298074,0.292797,0.432026,0.283947,0.560294
40,Colombia,74.999842,85.877334,83.481999,82.577769,77.087950,62.341043,64.037965,62.498065,61.094674,...,28.654305,27.215278,26.143867,25.551059,23.820759,23.399061,22.729608,25.677806,25.314110,NaN
41,Cook Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Costa Rica,4.452693,4.122197,4.871724,4.751393,5.273648,5.204833,5.222418,5.673052,5.921479,...,10.006043,11.560721,11.875905,12.273118,11.799546,11.261006,11.322284,11.620582,12.908902,17.745480
43,Croatia,2.833467,9.056700,8.092455,4.609130,3.058487,3.593571,2.674090,2.619532,2.361850,...,0.853186,0.884379,1.063716,1.127672,0.596293,0.827828,1.011645,0.840848,0.793442,NaN
44,Cuba,NaN,NaN,6.239685,7.397820,8.276670,7.798369,6.677607,6.792185,7.412971,...,5.316427,5.489991,5.077398,4.587552,4.373340,4.463151,NaN,NaN,NaN,NaN
45,Curaçao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Cyprus,0.634236,0.125165,0.246810,0.605302,0.828729,1.043242,1.135989,0.668473,0.765405,...,0.915293,1.230011,1.050834,0.558091,1.180417,1.165799,1.151855,1.214598,0.600885,0.817859
47,Czechia,NaN,NaN,NaN,NaN,2.005361,1.706742,1.680243,1.819057,1.695010,...,0.770165,0.836151,0.617170,0.626106,NaN,0.862161,0.606628,0.436819,0.824494,0.767828
48,Denmark,0.797506,1.319275,1.198909,1.368375,1.440593,1.127383,1.292022,1.665079,0.923785,...,1.311175,1.090839,0.977619,1.231534,1.001066,0.859902,0.823112,0.631747,0.982567,NaN
49,Dominica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.019986,...,12.788996,12.782275,22.986359,27.738644,19.068713,19.151303,22.198215,14.880510,28.431835,NaN

In [63]:
# Fill NaN values with the respective country's mean
pivot_df = pivot_df.set_index("Country").apply(lambda row: row.fillna(row.mean()), axis=1).reset_index()

In [65]:
pivot_df

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,6.003260,6.003260,6.003260,6.003260,6.003260,6.003260,6.003260,6.003260,6.003260,...,6.003260,9.952186,6.679997,6.792021,6.733248,7.163967,6.578109,4.032458,6.003260,6.003260
1,Albania,6.107501,6.107501,3.960395,5.827036,3.425695,7.948279,8.380375,41.304664,20.559899,...,4.614723,2.207938,2.726144,2.001213,2.280398,2.253026,2.123990,2.316086,1.697548,1.387083
2,Algeria,1.191346,1.191346,1.191346,1.191346,1.191346,1.191346,1.191346,1.191346,1.191346,...,1.471750,1.364334,1.326782,1.256917,1.336312,1.198765,1.484943,1.552688,1.748121,1.161072
3,American Samoa,7.076038,7.076038,7.076038,7.076038,7.076038,7.076038,7.076038,7.076038,7.076038,...,5.611043,7.564583,0.000000,13.569573,25.536011,0.000000,7.076038,7.076038,7.076038,7.076038
4,Andorra,0.583036,0.583036,0.583036,0.583036,0.583036,0.583036,0.583036,0.583036,0.583036,...,0.000000,0.000000,0.583036,0.583036,0.583036,0.583036,2.584647,0.583036,0.583036,0.583036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Venezuela (Bolivarian Republic of),12.477928,12.322151,15.716319,20.193351,21.785772,20.190305,21.891163,18.264990,19.278569,...,62.900609,51.200413,56.579205,47.979208,34.522099,41.032413,29.475380,19.279105,12.646645,34.522099
200,Viet Nam,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,...,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070,1.367070
201,Yemen,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588,3.334054,...,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588,4.287588
202,Zambia,7.063808,8.569657,9.392565,8.896669,9.689528,7.305078,7.305078,7.305078,9.195976,...,5.190209,5.201509,7.305078,7.305078,7.305078,7.305078,7.305078,7.305078,7.305078,7.305078
203,Zimbabwe,5.790507,8.713490,8.713490,8.713490,8.713490,8.713490,8.713490,8.713490,8.713490,...,8.713490,8.713490,8.713490,8.713490,4.882120,5.173080,8.713490,8.713490,8.713490,8.713490

In [64]:
pivot_df.to_csv('global_intentional_homicide_rates.csv',index=False)